<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="docom" nsURI="http://www.sourcepit.org/docom" nsPrefix="docom">
  <eClassifiers xsi:type="ecore:EClass" name="Paragraph" eSuperTypes="#//LiteralGroup #//Listable #//Structurable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Emphasis" eSuperTypes="#//Literal #//LiteralGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//EmphasisType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EmphasisType">
    <eLiterals name="ITALIC"/>
    <eLiterals name="BOLD" value="1" literal="BOLD"/>
    <eLiterals name="CODE" value="2"/>
    <eLiterals name="STRIKETHROUGH" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="#//Structurable #//Listable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ListType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ListItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" interface="true"
      eSuperTypes="#//Listable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Document" eSuperTypes="#//Structured"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ListType">
    <eLiterals name="UNORDERED"/>
    <eLiterals name="ORDERED" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chapter" eSuperTypes="#//Structurable #//Structured">
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" lowerBound="1"
        eType="#//Header" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralGroup" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="literals" upperBound="-1"
        eType="#//Literal" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Listable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Structurable" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Structured" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" upperBound="-1"
        eType="#//Structurable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" lowerBound="1"
        upperBound="-1" eType="#//Listable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Header" eSuperTypes="#//LiteralGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="Quote" eSuperTypes="#//Structured #//Structurable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Code" eSuperTypes="#//Structurable #//Listable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HorizontalLine" eSuperTypes="#//Structurable #//Listable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//LiteralGroup #//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//LiteralGroup #//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" eSuperTypes="#//Structurable #//Listable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeLiteral" eSuperTypes="#//Literal #//Listable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewLine" eSuperTypes="#//Structurable #//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Structurable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnDefinitions" unique="false"
        lowerBound="1" upperBound="-1" eType="#//Alignment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" lowerBound="1"
        eType="#//TableRow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" upperBound="-1"
        eType="#//TableRow" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Alignment">
    <eLiterals name="LEFT"/>
    <eLiterals name="CENTER" value="1"/>
    <eLiterals name="RIGHT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cells" lowerBound="1" upperBound="-1"
        eType="#//TableCell" containment="true" eOpposite="#//TableCell/row"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableCell" eSuperTypes="#//LiteralGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" lowerBound="1" eType="#//TableRow"
        eOpposite="#//TableRow/cells"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnSpan" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
</ecore:EPackage>
